name: personal_os_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.5

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7
  flutter_riverpod: ^3.4.3
  forui: ^0.27.4
  intl: ^0.20.3
  material_ui: ^1.5.0
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
